import type { Metadata } from "next";
import { Instrument_Serif } from "next/font/google";
import "./globals.css";

const instrument = Instrument_Serif({
  weight: ["400"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Motion Playground",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${instrument.className} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
